---
title: "Introduction to Xsurv"
description: >
  This vignette describes the basic workflow of Xsurv.
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to Xsurv}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}

---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  fig.width = 6,
  fig.height = 5
)
```

## Introduction

`Xsurv` is an R package used for interpretation of advanced machine learning methods for survival data.


## Installation

### Latest release on GitHub

```{r}
#install.packages('devtools')  Ignore this if devtools is already installed.
devtools::install_github('topycyao/Xsurv')
```
## Quick start

**1) Load the package

```{r}
library(Xsurv) #Load Xsurv into R

```
**2) Xsurv can help to generate survival data
```{r}
sim_dat<-Xsurv_sim_data(size=500,dim=20,lambda=2,vu=1, 
                                    c_rate=0.3)   # A data set is generated with sample size =500

#Covariates and survival outcome should be separted before fitting to Xsurv models
sim_x<-sim_dat[,1:20] # The first 20 (equal to dimension of covariates) columns
sim_y<-sim_dat[,c(21,22)] # The last 2 columns
```
**3) Quick fit from data
```{r}

fit<-Xsurv.cv(sim_x,sim_y,top_n=3)

```
